version: '3.8'
services:
  fhirflare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
      - ./hapi-fhir-jpaserver/target/h2-data:/app/h2-data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - NODE_PATH=/usr/lib/node_modules
    command: supervisord -c /etc/supervisord.conf